# Generated by Django 5.2.5 on 2025-08-30 18:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('id_unico_qr', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID do QR Code')),
                ('qr_code_img', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='Imagem do QR Code')),
            ],
        ),
    ]
