# Generated by Django 5.2.5 on 2025-08-30 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Evento')),
                ('data', models.DateTimeField(verbose_name='Data e Hora')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('PRESENTE', 'Presente'), ('LISTA_ESPERA', 'Lista de Espera')], default='INSCRITO', max_length=20)),
                ('data_checkin', models.DateTimeField(blank=True, null=True, verbose_name='Data do Check-in')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.participante')),
            ],
            options={
                'unique_together': {('participante', 'evento')},
            },
        ),
    ]
