# Generated by Django 5.2.5 on 2025-08-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='vagas',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de Vagas'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_entrada_espera',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entrada na Lista de Espera'),
        ),
    ]
