# Generated by Django 5.2.5 on 2025-10-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento_vagas_inscricao_data_entrada_espera'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='ultimo_envio_email',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Envio do E-mail'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='matricula',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Matrícula'),
        ),
    ]
